const app=document.getElementById('app');
const savedKey=localStorage.getItem('tornApiKey');
const TORN_API='https://api.torn.com/v2';
const defaultStats=[{id:'level',label:'Level',path:'profile.level'},{id:'money',label:'Cash',path:'money.cash'},{id:'energy',label:'Energy',path:'bars.energy.current'},{id:'nerve',label:'Nerve',path:'bars.nerve.current'},{id:'happy',label:'Happy',path:'bars.happy.current'},{id:'life',label:'Life',path:'bars.life.current'},{id:'rank',label:'Rank',path:'profile.rank'},{id:'networth',label:'Net Worth',path:'networth.total'}];
let selectedStats=JSON.parse(localStorage.getItem('tornTrackerStats')||'null')||defaultStats,userData={};
const money=n=>typeof n==='number'?'$'+n.toLocaleString('en-US'):String(n??'—');
const getPath=(o,p)=>p.split('.').reduce((v,k)=>v==null?undefined:v[k],o);
const esc=s=>String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\':'&#92;','"':'&quot;'}[c]));

// GitHub Pages cannot execute /api/torn.js. TornTracker therefore calls Torn's
// read-only API directly. The key is read from localStorage and is only sent to api.torn.com.
async function torn(path,key){
  try{
    const r=await fetch(TORN_API+path,{headers:{Authorization:`ApiKey ${key}`,Accept:'application/json'}});
    const text=await r.text();
    let d;try{d=JSON.parse(text)}catch{throw new Error(`Torn API hat keine gültige JSON-Antwort geliefert (HTTP ${r.status}).`)}
    if(!r.ok)throw new Error(d?.error?.error||d?.error?.message||`Torn API Fehler (HTTP ${r.status}).`);
    if(d?.error)throw new Error(d.error.error||d.error.message||'Torn API Fehler.');
    return d;
  }catch(e){
    if(e instanceof TypeError)throw new Error('Torn API konnte nicht erreicht werden. Prüfe deine Internetverbindung oder ob der Browser die Verbindung blockiert.');
    throw e;
  }
}
function login(error=''){app.innerHTML=`<main class="login"><div class="eyebrow">TornTracker</div><h1>Verbinde deinen Torn-Account</h1><p class="muted">Gib deinen Torn API-Key ein, um dein persönliches Dashboard zu verwenden.</p><input id="apiKey" class="field" type="password" autocomplete="off" placeholder="Torn API-Key"><button class="primary" id="connect">Verbinden</button><button class="secondary create-key" id="createKey">🔑 Limited API-Key erstellen</button><div class="privacy"><strong>🔒 Dein API-Key bleibt auf deinem Gerät</strong><br><span>Der Key wird ausschließlich lokal in diesem Browser gespeichert und nicht von TornTracker auf GitHub veröffentlicht.</span></div><div class="key-help"><strong>⚠️ Bitte einen „Limited Access“ API-Key verwenden.</strong><br><span>Dieser Zugriff reicht für die TornTracker-Funktionen aus.</span></div><div id="error" class="error">${esc(error)}</div></main>`;document.getElementById('createKey').onclick=()=>window.open('https://www.torn.com/preferences.php#tab=api?&step=addNewKey&title=TornTracker&type=3','_blank','noopener,noreferrer');document.getElementById('connect').onclick=async()=>{const key=document.getElementById('apiKey').value.trim(),err=document.getElementById('error');if(!key){err.textContent='Bitte einen API-Key eingeben.';return}if(!/^[A-Za-z0-9]{16}$/.test(key)){err.textContent='Der Torn API-Key muss 16 Zeichen lang sein.';return}err.textContent='API-Key wird geprüft…';try{await torn('/user/basic',key);localStorage.setItem('tornApiKey',key);location.reload()}catch(e){err.textContent=e.message}}}
async function loadDashboard(){try{const [basic,bars,moneyData,networth]=await Promise.all([torn('/user/basic',savedKey),torn('/user/bars',savedKey),torn('/user/money',savedKey),torn('/user/networth',savedKey)]);userData={...basic,bars:bars.bars||bars,money:moneyData.money||moneyData,networth:networth.networth||networth};dashboard()}catch(e){localStorage.removeItem('tornApiKey');login(e.message)}}
function dashboard(){app.innerHTML=`<div class="shell"><header class="topbar"><div class="brand">Torn<span>Tracker</span></div><button class="menu-btn" id="menu">☰</button></header><main class="content"><section class="welcome"><div class="eyebrow">Dashboard</div><h1>${esc(getPath(userData,'profile.name')||'Dein Torn-Account')}</h1><p class="muted">Deine ausgewählten Statistiken.</p></section><div class="toolbar"><button class="secondary" id="customize">⚙ Statistiken anpassen</button><button class="secondary" id="refresh">↻ Aktualisieren</button></div><section class="grid" id="stats"></section></main></div><div id="overlay" class="overlay hidden"></div><aside id="drawer" class="drawer hidden"><button class="menu-btn" id="close">×</button><h2>Menü</h2><div class="nav"><button data-page="dashboard">📊 Dashboard</button><button data-page="market">🏪 Item Market</button><button data-page="bazaar">🛒 Bazaar</button><button data-page="settings">⚙ Einstellungen</button><button id="logout">🔑 API-Key löschen</button></div></aside>`;renderStats();wireMenu();document.getElementById('customize').onclick=openCustomizer;document.getElementById('refresh').onclick=loadDashboard}
function renderStats(){const c=document.getElementById('stats');c.innerHTML='';selectedStats.forEach(s=>{let v=getPath(userData,s.path);if(['money','networth'].includes(s.id))v=money(v);c.innerHTML+=`<article class="card"><div class="label">${esc(s.label)}</div><div class="value">${esc(v??'—')}</div></article>`})}
function openCustomizer(){const choices=[...defaultStats,{id:'crime',label:'Crimes',path:'personalstats.crimes.total'},{id:'attacks',label:'Attacks Won',path:'personalstats.attackswon.total'},{id:'defends',label:'Defends Won',path:'personalstats.defendswon.total'}];app.insertAdjacentHTML('beforeend',`<div class="modal-wrap" id="customModal"><div class="modal"><h2>Statistiken auswählen</h2><p class="muted">Wähle die Karten für dein Dashboard.</p><div class="checks">${choices.map(s=>`<label><input type="checkbox" value="${s.id}" ${selectedStats.some(x=>x.id===s.id)?'checked':''}> ${esc(s.label)}</label>`).join('')}</div><div class="modal-actions"><button class="secondary" id="cancel">Abbrechen</button><button class="primary small-btn" id="save">Speichern</button></div></div></div>`);document.getElementById('cancel').onclick=()=>document.getElementById('customModal').remove();document.getElementById('save').onclick=()=>{selectedStats=choices.filter(s=>document.querySelector(`.checks input[value="${s.id}"]`)?.checked);if(!selectedStats.length)selectedStats=[defaultStats[0]];localStorage.setItem('tornTrackerStats',JSON.stringify(selectedStats));document.getElementById('customModal').remove();renderStats()}}
function wireMenu(){document.getElementById('menu').onclick=()=>toggle(true);document.getElementById('close').onclick=()=>toggle(false);document.getElementById('overlay').onclick=()=>toggle(false);document.getElementById('logout').onclick=()=>{localStorage.removeItem('tornApiKey');location.reload()};document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>page(b.dataset.page))}
function toggle(open){document.getElementById('drawer').classList.toggle('hidden',!open);document.getElementById('overlay').classList.toggle('hidden',!open)}
function page(name){toggle(false);if(name==='market'||name==='bazaar')marketPage(name);if(name==='settings')openCustomizer()}
function marketPage(type){const title=type==='market'?'Item Market':'Bazaar';app.innerHTML=`<div class="shell"><header class="topbar"><div class="brand">Torn<span>Tracker</span></div><button class="menu-btn" id="menu">☰</button></header><main class="content"><section class="welcome"><div class="eyebrow">${title}</div><h1>Aktuelle Preise</h1><p class="muted">Suche nach einer Item-ID und vergleiche Angebote.</p><div class="search-line"><input id="itemSearch" class="field search" placeholder="Item-ID"><button class="primary search-btn" id="search">Suchen</button></div><div id="marketError" class="error"></div></section><section class="card" id="marketResults"><div class="muted">Noch keine Suche.</div></section></main></div><div id="overlay" class="overlay hidden"></div><aside id="drawer" class="drawer hidden"><button class="menu-btn" id="close">×</button><h2>Menü</h2><div class="nav"><button data-page="dashboard">📊 Dashboard</button><button data-page="market">🏪 Item Market</button><button data-page="bazaar">🛒 Bazaar</button><button data-page="settings">⚙ Einstellungen</button><button id="logout">🔑 API-Key löschen</button></div></aside>`;wireMenu();document.getElementById('search').onclick=()=>searchMarket(type)}
async function searchMarket(type){const q=document.getElementById('itemSearch').value.trim(),out=document.getElementById('marketResults'),err=document.getElementById('marketError');if(!q){err.textContent='Bitte eine Item-ID eingeben.';return}if(!/^\d+$/.test(q)){err.textContent='Bitte eine numerische Item-ID verwenden.';return}err.textContent='';out.innerHTML='<div class="muted">Lade Marktdaten…</div>';try{const d=await torn(`/market/${q}/${type==='market'?'itemmarket':'bazaar'}`,savedKey);const listings=d.itemmarket||d.bazaar||d.listings||[];renderMarket(out,{listings:Array.isArray(listings)?listings:[]})}catch(e){out.innerHTML='';err.textContent=e.message}}
function renderMarket(out,data){const rows=Array.isArray(data.listings)?data.listings:[];if(!rows.length){out.innerHTML='<div class="muted">Keine Angebote gefunden.</div>';return}out.innerHTML=`<div class="market-row header-row"><strong>Verkäufer</strong><strong>Preis</strong><strong>Menge</strong></div>`+rows.slice(0,100).map(x=>`<div class="market-row"><span>${esc(x.seller||x.player_name||x.player?.name||'Unbekannt')}</span><span>${money(x.price)}</span><span>${esc(x.quantity??x.amount??'1')}</span></div>`).join('')}
if(savedKey)loadDashboard();else login();
